### ISSUE TITLE
Can't copy a relation if a at least 2 roles are played by the same entity

### ISSUE THREAD

**Issue by lveillard** [vaticle/typedb#6758] opened 2023-03-04 17:51 UTC
## Schema
```java
define
id sub attribute, value string;

year sub entity, owns id @key, plays teaching:year;
person sub entity, owns id @key, plays teaching:teacher, plays teaching:student;
teaching sub relation, relates teacher, relates student, relates year, owns id @key;

insert
$a isa person, has id '1';
$b isa person, has id '2';
$c isa person, has id '3';
$y isa year, has id '2000';
$t (teacher: $a, student: $a, student: $b, year: $y )isa teaching, has id 't'; 
```
## query
```java
match
$teaching ($id) isa teaching, has id 't';

insert
$t ($id) isa teaching, has id 't2';
```

## Expected:
Generate a $teaching relation that copies the roles into the new 't2' relation

## Current:
Error> [THW28] Invalid Thing Write: Unable to add role player '$id' to the relation, as there are more than one possible role type it could play.

## Alternative
Trying to map also the roles's types:
```
match
$teaching ($roleType:$id) isa teaching, has id 't';

insert
$t ($roleType:$id) isa teaching, has id 't2';
```

throws the following error:
`## Error> [THW16] Invalid Thing Write: Illegal type variable '$roleType' found in insert query. Types can only be referred to by their labels in insert queries or then clauses.`

**Comment by lveillard** [comment] 2023-03-05 15:45
Also, a related issue, same schema but with 3 roles that have no intersection (no thing plays more than 1 role):
![image](https://user-images.githubusercontent.com/29461076/222970648-3714233d-9392-4576-a99b-711e53269821.png)

So basically `$p3 ($id) isa process, has id 'p3';` 

Creates as many relations as nodes in $id, instead of one single relation that copies the roles of 'p1'

**Comment by lveillard** [comment] 2023-06-02 10:33
@flyingsilverfin probably the best would be to enable using $roleType in inserts and deletions.

The most complicated test to design is a 3 role relation, where 2 roles can be played by the same entity, and then unlink all those units in one of those 2 roles

As the result, a node that was playing the two roles, must be unlinked only in the roles that match $roleType.

```bash
match
$teaching ($roleType:$id) isa teaching, has id 't';
{$roleType type teaching:student;} or {$roleType type year;};

delete
$t ($roleType:$id) isa teaching, has id 't2';
```

**Comment by izmalk** [comment] 2023-06-02 11:10
First, I needed to fix the schema definition query a little to be able to reproduce the issue:
```
define
year sub entity, owns id, plays teaching:year;
person sub entity, owns id, plays teaching:teacher, plays teaching:student;
teaching sub relation, relates teacher, relates student, relates year, owns id;
id sub attribute, value string;
```

Initial insert query is fine.

The state of the data on this point is the following:
![Screenshot 2023-06-02 at 12 02 09](https://github.com/vaticle/typedb/assets/48120135/f8638b04-4e3d-4428-9b55-425592174d5f)

To achieve what you ask in a single query is kinda hard. Since `match-insert` will insert a separate relation for every matched result. Hence, we need at least two separate `match-insert` queries to achieve the result. 
The first query inserts the relation with id `t2`:
```
match
$teaching (teacher: $teacher, student:$student, year: $year) isa teaching, has id 't';
insert
$t (teacher: $teacher, year: $year) isa teaching, has id 't2';
```
and the second query matches the new relation and inserts roles into it:
```

**Comment by lveillard** [comment] 2023-06-04 14:19
Hello @izmalk and thanks for your answer!

There are two key things in this issue, one that you identified which is being able to do this kind of mutations in a single stream. Some use cases are not compatible with multistreams ($vars are not shared between streams) as well as some impact on performance. 

I spent days looking for a one stream solution and tried 4 or 5 different approaches (some really weird ones) without succes. I dont think it is possible.

The second key thing on the issue is that is that the mutation is dynamically built, which explains why im using "$roleType" instead of particular role names

I think the best example is the last one I've provided with the deletion.

Enabling types in inserts and deletions might be the easiest way to unblock this use case, but I guess there is a good reason behind this limitation.

I think I get why its forbidden in inserts, but maybe it is ok for deletions 🤔

**Comment by flyingsilverfin** [comment] 2023-06-07 16:47
FYI one thing that would set the right `$roleType` if it could be used in `insert` and `delete` clauses is:
```
match $r ($roleType: $x) isa! $relType; $roleType relates $relType;
```
will enforce that this is the exact role type played by the role player in this relation.

Bit convoluted, but best we ahve right now.

I think with this and allowing types variable in the `insert` and `delete` blocks you can solve this issue and also https://github.com/vaticle/typedb/issues/6755 right?

**Comment by lveillard** [comment] 2023-06-07 22:41
Yay! That will probably make it for both cases.

The key edge use-case I would build for specs, is having one entity playing two roles, ensuring that copy works as intended, and deletions only affect the filtered roleTypes.

Btw, to adapt this:
`match $r ($roleType: $x) isa! $relType; $roleType relates $relType;` 
to my example
 `{$roleType type teaching:student;} or {$roleType type teaching:year;};`
would be like this?
` {$roleType relates student;} or {$roleType relates year;};`

Thanks!

**Comment by flyingsilverfin** [comment] 2023-06-09 09:05
i think you'd have to do `{ student plays $roleType; }`

**Comment by flyingsilverfin** [comment] 2023-09-05 12:01
Closing as this is resolvable with a combination of https://github.com/vaticle/typedb/pull/6883 and https://github.com/vaticle/typedb/pull/6883

**Closed by flyingsilverfin** 2023-09-05 12:01 UTC
