### ISSUE TITLE
Unable to start Storage when starting Grakn Docker

### ISSUE THREAD

**Issue by neomatrix369** [vaticle/typedb#5570] opened 2020-01-30 16:01 UTC
## Description

Started Grakn docker container and get the below error in the docker console:

```
Version: 1.5.7
Starting Storage......FAILED!
Unable to start Storage. 
```

This is intermittent, does happen all the time. Is this resolved in the later versions? For now, I would like to continue to use 1.5.7.

## Environment

1. OS (where Grakn server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. Grakn version (and platform): 1.5.7 or 1.6.2
3. Grakn client: n/a
4. Other environment details:
Docker container: version 19.03.5
JDK used: GraalVM CE 19.2.1 (I also run it under OpenJDK8 at times)

Some more config related details:
JAVA_HOME=/usr/local/graalvm-ce-19.2.1
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
STORAGE_JAVAOPTS=-XX:+UseJVMCINativeLibrary -XX:+UseJVMCINativeLibrary
SERVER_JAVAOPTS=-XX:+UseJVMCINativeLibrary -XX:+UseJVMCINativeLibrary
GRAKN_DAEMON_JAVAOPTS=-XX:+UseJVMCINativeLibrary -XX:+UseJVMCINativeLibrary

_Note: please don't get confused by JDK8 strings above, GraalVM is based on JDK8._

## Reproducible Steps

Usual `grakn start server` command inside a container, please try using [this](https://github.com/neomatrix369/awesome-ai-ml-dl/tree/master/examples/data/databases/graph/grakn). 

Use the command:

```
$ GRAKN_VERSION=1.6.2 ./grakn-runner.sh --runContainer
or
$ GRAKN_VERSION=1.6.2 ./grakn-runner.sh --jdk GRAALVM --runContainer
```

to see it try to start the Grakn 1.6.2 inside the container. As I said it's intermittent and might be free space related. 

Will report with the relevant logs when it happens again.

## Expected Output

An up and running Grakn server

## Actual Output

See in description above.
 
## Additional information

At the time of the reporting, I didn't have the log files as it was a closed and deleted container but have since then made changes to the script to mount a volume outside the container to generate the log files, see [issue](https://github.com/graknlabs/grakn/issues/5565).

On the back of the [slack channel discussions](https://grakn-community.slack.com/archives/C3DS7RW2J/p1580049491044900)

**[cassandra.log](https://github.com/graknlabs/grakn/files/4136031/cassandra.log)**
**[grakn.log](https://github.com/graknlabs/grakn/files/4136032/grakn.log)**

**Comment by neomatrix369** [comment] 2020-01-30 20:15
@kasper-piskorski I have attached the logs to the issue - it occurred the again today and I hope the logs tell you what went wrong because there are times when it works fine.

**Comment by neomatrix369** [comment] 2020-02-01 11:13
I have another set of logs and this time it occurred when running OpenJDK:

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
JAVA_HOME=/usr/local/openjdk-8/
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
Grakn version:  1.6.2

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting Storage.........FAILED!
Unable to start Storage.
```

I have attached the requested logs.

[cassandra.log](https://github.com/graknlabs/grakn/files/4142461/cassandra.log)
[grakn.log](https://github.com/graknlabs/grakn/files/4142462/grakn.log)

**Comment by SamuelHassine** [comment] 2020-02-23 08:45
A lot of OpenCTI users are encountered the same issue. I was able to reproduce by using Docker in the latest Ubuntu 19.10 on a SATA disk using volumes for persistence.

**Comment by neomatrix369** [comment] 2020-03-02 15:54
> A lot of OpenCTI users are encountered the same issue. I was able to reproduce by using Docker in the latest Ubuntu 19.10 on a SATA disk using volumes for persistence.

Do you have any fix for it, that you would like to share?

**Comment by SamuelHassine** [comment] 2020-03-03 12:56
@neomatrix369 : https://github.com/OpenCTI-Platform/opencti/issues/137#issuecomment-593924221

**Comment by richard-julien** [comment] 2020-03-06 21:38
Just a hint (maybe). Looks like is related to the number of dependencies that starting at the same time in the compose file.

**Comment by SamuelHassine** [comment] 2020-03-07 09:08
Another hint: Starting Grakn Docker with a volume for persistence on a SATA disk will lead to this problem after restart (first run is ok, second one is broken).

**Comment by SamuelHassine** [comment] 2020-03-08 17:38
Is it possible to have an explanation about the closing of this issue?

**Comment by neomatrix369** [comment] 2020-03-09 12:09
> Another hint: Starting Grakn Docker with a volume for persistence on a SATA disk will lead to this problem after restart (first run is ok, second one is broken).

This works fine on the MacOS but volumes need to be mounted differently on Linux. I have discussed this with some other folks and they say, that when we mount the volume we got to ensure that the UID and GID inside and outside the containers must be the same, they should match (the user's UID and Groups GID that is). I haven't applied this solution yet but like everyone else it's on my TODO list.

This can become tricky if we have a user created inside the container (using the USER or --user flags/CLI options).

**Comment by flyingsilverfin** [comment] 2020-03-09 19:37
Apologies, it was accidental!

**Comment by SamuelHassine** [comment] 2020-03-10 11:04
Hello,

Just a linked problem to that is when the container starts and log: `====================================================================================================
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|

                                         THE KNOWLEDGE GRAPH
====================================================================================================
                                                                                      Version: 1.6.2

Starting Storage.......FAILED!
Unable to start Storage.`

The container never stops! The expected behavior is that the container stops and tries to restart. But it is stuck indefinitely.

**Comment by lolski** [comment] 2020-03-11 20:11
I managed to consistently start Grakn Docker successfully in a Ubuntu machine.

```
$ docker run --name grakn graknlabs/grakn:latest
====================================================================================================
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|

                                         THE KNOWLEDGE GRAPH
====================================================================================================
                                                                                      Version: 1.6.2
Starting Storage......SUCCESS
Starting Grakn Core Server......SUCCESS
2020-03-11 20:08:49,439 [main] INFO  grakn.core.server.Grakn - Grakn started in 1.339 s
```
Here's the detailed information regarding the environment:

Operating System
```
root@lolski-test:~# lsb_release -d
Description:	Ubuntu 19.10
```

Docker version
```
root@lolski-test:~# docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Grakn version
```
Version: 1.6.2
```

> Another hint: Starting Grakn Docker with a volume for persistence on a SATA disk will lead to this problem after restart (first run is ok, second one is broken).

I have not yet tried starting the container with a SATA disk. If you know how to set a SATA disk on the Google Cloud Platform, let us know so we can try it out more quickly @SamuelHassine

**Comment by richard-julien** [comment] 2020-04-06 08:48
It seems that starting grakn alone is fine. As soon as you start it with a bunch of other containers it starts to fail. Please can you try to deploy the openCTI stack and see what happen? Thanks

**Comment by richard-julien** [comment] 2020-04-06 09:29
For info. All tickets related to this problem. 
Workaround is to start grakn in another stack or not in docker. Thanks
https://github.com/OpenCTI-Platform/opencti/issues/137
https://github.com/OpenCTI-Platform/opencti/issues/542
https://github.com/OpenCTI-Platform/opencti/issues/547
https://github.com/OpenCTI-Platform/opencti/issues/603

**Comment by richard-julien** [comment] 2020-04-15 15:32
Hi, any news, progress on that? Thanks

**Comment by lolski** [comment] 2020-05-04 15:13
Sorry! We haven't made progress here since we were unable to reproduce it.

There is, however, a PR by a community member that would allow the timeout to be configurable: https://github.com/graknlabs/grakn/pull/5710

Assuming that Cassandra just needs longer to boot up when there are more data / the CPU is busy, adjusting the timeout would help.

What do you guys think @richard-julien @SamuelHassine @neomatrix369 ?

**Comment by richard-julien** [comment] 2020-05-04 15:30
It seems it could solve the problem.
Please also integrate in the PR that the timeout must exit(1) the grakn process.

**Comment by flyingsilverfin** [comment] 2021-04-22 16:15
Please re-open if this is an issue in 2.0, however we no longer use cassandra as our storage engine!

**Closed by flyingsilverfin** 2021-04-22 16:15 UTC
Labels: type: bug
