### ISSUE TITLE
Support ARM processors using aarch64 (new Apple hardware, Raspberry Pi's)

### ISSUE THREAD

**Issue by PaulDoxey** [vaticle/typedb#6255] opened 2021-03-15 20:55 UTC
## Problem to Solve

Currently Grakn only supports x86_64-based machines running macOS, Linux or Windows. It does not run on Raspberry Pi's and Macs that have the new Apple hardware using the aarch64 architecture. Therefore users and developers with these new Macs or with Raspberry Pi's can't use Grakn on them.

## Current Workaround

Grakn must be run on x86_64-based machines running macOS, Linux or Windows. This limits the use cases for Grakn and reduces its exposure to users who do not have this architecture.

## Proposed Solution

Grakn could develop solutions for devices with the Arm chipset/aarch64 architecture. 

Having such a solution could be useful for Apple users with the new Apple Silicon Arm chips. 

It would also expand Grakn's market to include the cheap Raspberry Pi's, e.g. for intelligent data-driven devices running on an embedded Raspberry Pi. This is sounds like a potentially-disruptive market opportunity.

**Comment by DiligentDilettante** [comment] 2021-03-16 16:56
Does it not? RocksDB supports Arm, and the rest of Grakn seems to be (from what I've seen) stuff that runs on the JVM.

**Comment by PaulDoxey** [comment] 2021-03-16 18:31
> Does it not? RocksDB supports Arm, and the rest of Grakn seems to be (from what I've seen) stuff that runs on the JVM.

No, Grakn does not currently work on Arm - the information raised in the issue is from the Grakn team.

**Comment by haikalpribadi** [comment] 2021-03-20 22:45
I haven't explicitly tested Grakn to run on Arm or the new Mac processors, but is there a reason why Grakn shouldn't work on them? Have we actually tested it, @PaulDoxey ? There shouldn't be any reason why Grakn wouldn't run on them, right? Or am I missing something, @flyingsilverfin @lolski ?

**Comment by haikalpribadi** [comment] 2021-03-20 22:45
ps: @PaulDoxey you can remove the curly brackets in the issue template once you fill in the text. I've edited the issue above accordingly.

**Comment by PaulDoxey** [comment] 2021-03-20 23:02
Yes @Haikal ***@***.***>, this is based on trying it. This issue arose because I installed Grakn 2.0.0 on a Rapsberry Pi 400 (64 bit Arm) running Ubuntu and it generated an error, which I reported on Discord with full details. I did not get the error when I installed it on Ubuntu on a VM running on a 2015 MacBook Pro (Intel). The reply from Max cc Ganesh was exactly as I have reproduced it in the GitHub repo.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by haikalpribadi** [comment] 2021-03-20 23:10
Can you share the error message from running Grakn 2.0 on Raspberry Pi here so we can learn the specific cause, @PaulDoxey ?

**Comment by PaulDoxey** [comment] 2021-03-20 23:14
> Can you share the error message from running Grakn 2.0 on Raspberry Pi here so we can learn the specific cause, @PaulDoxey ?

It's on Discord (Troubleshoot channel) but here it is again:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
    at grakn.core.server.GraknServer.<init>(GraknServer.java:89)
    at grakn.core.server.GraknServer.startGraknServer(GraknServer.java:275)
    at grakn.core.server.GraknServer.main(GraknServer.java:234)
Caused by: java.lang.NullPointerException: Resource linux-aarch64/ was not found in ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc
    at java.base/java.util.Objects.requireNonNull(Objects.java:246)
    at com.google.ortools.Loader.getNativeResourceURI(Loader.java:25)
    at com.google.ortools.Loader.loadNativeLibraries(Loader.java:83)
    at grakn.core.rocks.RocksGrakn.<clinit>(RocksGrakn.java:48)
    ... 3 more
```

**Comment by haikalpribadi** [comment] 2021-03-20 23:21
Okay that seems to be related to the linear solver library used for the query planning algorithm. That's good to know. We can proceed to find a way to extend the library to work with linux-aarch64.

**Comment by flyingsilverfin** [comment] 2021-03-21 12:36
Yeah ARM is a different CPU architecture so we'll need different RocksDB and OrTools binaries for that

**Comment by flyingsilverfin** [comment] 2021-03-21 12:36
The new M1 macs are OK because they can emulate the x86 CPU architecture if its not compiled for ARM natively

**Comment by vmax** [comment] 2021-04-16 13:02
Blocked by facebook/rocksdb#7720

**Comment by vmax** [comment] 2021-04-22 16:59
Looks like upgrading OrTools to a version that includes google/or-tools#716 should resolve the issue for Raspberry PIs; as stated, RocksDB already supports `linux-aarch64`

**Comment by FedericoCampe8** [comment] 2021-05-12 02:38
Any news on this? Same problem here, mac m1 but cannot run server
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/bn/3g12xx8d3wq5byr9fx5ccqdm0000gn/T/librocksdbjni17941711089876951568.jnilib: dlopen(/private/var/folders/bn/3g12xx8d3wq5byr9fx5ccqdm0000gn/T/librocksdbjni17941711089876951568.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/bn/3g12xx8d3wq5byr9fx5ccqdm0000gn/T/librocksdbjni17941711089876951568.jnilib: mach-o, but wrong architecture
	/private/var/folders/bn/3g12xx8d3wq5byr9fx5ccqdm0000gn/T/librocksdbjni17941711089876951568.jnilib: mach-o, but wrong architecture
```
Now, I can use the docker which gives me a worning

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

If I run the docker, I cannot connect the client:
$ ./grakn console --cluster=localhost:1729

Welcome to Grakn Console. You are now in Grakn Wonderland!
Copyright (C) 2021 Grakn Labs

[CLI11] Client Error: Unable to connect to Grakn Cluster. Attempted connecting to the cluster members, but none are available: 'localhost:1729'.

As of now, Grakn Wonderland is not that great...

**Comment by flyingsilverfin** [comment] 2021-05-12 15:34
@haikalpribadi  do you think we can should bump OR-Tools and give it a shot? Might then work by itself... @vmax does that sound about right?

**Comment by vmax** [comment] 2021-05-12 15:44
@flyingsilverfin I couldn't find any _released_ version of OR-Tools for ARM. We could try:

* cross-compiling
* renting ARM machine from AWS and compiling it there
* letting upstream (OR-Tools) know that we want ARM libraries published

**Comment by vmax** [comment] 2021-05-12 15:47
@FedericoCampe8 I believe your problem with connection might be caused by using the wrong option (`--cluster`). Could you try swapping that to `--server=localhost:1729`, test again and let us know?

**Comment by flyingsilverfin** [comment] 2021-05-12 15:51
@vmax  can you bring this up in our next weekly meeting? I think we should have one monday, otherwise lets have a chat about it next week separately too

**Comment by FedericoCampe8** [comment] 2021-05-12 16:35
@vmax that is correct, I double checked my side and cluster makes no sense since I'm running the server.
So, only the arch problem remains open.

**Comment by KnowledgeGarden** [comment] 2022-02-08 01:59
This may or may not apply
https://github.com/adamretter/rocksdb/tree/macos-multi-arch

**Comment by marvin-hansen** [comment] 2022-03-09 03:00
I can't even install on MacOS 12 (Monteray) using Brew. 
Getting this error:

'n$ brew tap vaticle/tap
==> Tapping vaticle/tap
Cloning into '/opt/homebrew/Library/Taps/vaticle/homebrew-tap'...
remote: Enumerating objects: 412, done.
remote: Counting objects: 100% (308/308), done.
remote: Compressing objects: 100% (209/209), done.
remote: Total 412 (delta 80), reused 284 (delta 58), pack-reused 104
Receiving objects: 100% (412/412), 58.33 KiB | 1.10 MiB/s, done.
Resolving deltas: 100% (110/110), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/vaticle/homebrew-tap/Formula/grakn-core.rb
grakn-core: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the vaticle/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/vaticle/homebrew-tap/Formula/grakn-core.rb:24

Error: Cannot tap vaticle/tap: invalid syntax in tap!
' 

I guess the tap needs an update...

**Comment by alexjpwalker** [comment] 2022-03-10 09:48
TypeDB doesn't use the `vaticle/tap` anymore, @marvin-hansen . Please simply run `brew install typedb` to install it.

I'll update the TypeDB installation docs to reflect this.

**Comment by marvin-hansen** [comment] 2022-03-10 10:04
Excellent.

Thanks for the update.  Please update documentation to ensure people have a
smooth first Impression.



Marvin Hansen
https://www.linkedin.com/in/marvin-hansen/

**Comment by haikalpribadi** [comment] 2022-09-25 20:21
For the new Apple Silicon architecture, the problem has been solved, please refer to: https://github.com/vaticle/typedb/issues/6442#issuecomment-1257271202

**Comment by flyingsilverfin** [comment] 2022-10-21 14:01
We will be working on a native ARM build of TypeDB in the next week or two!

**Comment by FedericoCampe8** [comment] 2023-04-24 00:36
> For the new Apple Silicon architecture, the problem has been solved, please refer to: [#6442 (comment)](https://github.com/vaticle/typedb/issues/6442#issuecomment-1257271202)

not true

**Comment by dmitrii-ubskii** [comment] 2023-04-24 11:59
Replied to @FedericoCampe8's comment in https://github.com/vaticle/typedb/issues/6442#issuecomment-1520011502

**Comment by phvheumen** [comment] 2023-06-02 12:33
Is there perhaps any update on the ARM build for typeDB? As far as I can see, only the `ortools` dependency is the problem. From what I understand, `ortools` v8.x has ARM support, but the dependency is explicitly specified as x86_64. I have been trying to pull the aarch64 one instead, but I could not find a Maven repository with the aarch64 variant v8.x (only v9.x, but I'm not sure it is wise to jump major version without understanding the implications). 

Since I am not familiar at all with Bazel, Maven, and OR tools, I did not put too much effort yet into trying to make an ARM build work.

**Comment by flyingsilverfin** [comment] 2023-07-06 09:24
Hi all, 
We're happy to say that the new TypeDB release (2.19.0) is natively runnable on both Linux and Mac `arm` architectures :) Please feel free to download it via the relevant package manager (brew/apt) or from: https://github.com/vaticle/typedb/releases

**Comment by flyingsilverfin** [comment] 2023-07-06 09:25
For Mac users, you can now install `java` and `typedb` via brew without any more workarounds! Very exciting :)

**Closed by flyingsilverfin** 2023-07-06 09:25 UTC
Labels: type: feature, priority: high
