### ISSUE TITLE
Race condition in key uniqueness

### ISSUE THREAD

**Issue by SamuelHassine** [vaticle/typedb#5587] opened 2020-02-23 08:37 UTC
## Description

We thought that since the Grakn Core 1.6.X key uniqueness has been correctly enforced. In some very rare conditions (first time in different deployments), we managed to encounter a race condition in the key insertion:

```
grakn> match $type key stix_id_key; $type type Attack-Pattern; get;
{$type type Attack-Pattern sub Stix-Domain-Entity;}
grakn> match $x id V18915440, has stix_id_key $s; get;
{$s "attack-pattern--f4882e23-8aa7-4b12-b28a-b349c12ee9e0" isa stix_id_key; $x id V18915440 isa Attack-Pattern;}
grakn> match $x id V37974264, has stix_id_key $s; get;
{$s "attack-pattern--f4882e23-8aa7-4b12-b28a-b349c12ee9e0" isa stix_id_key; $x id V37974264 isa Attack-Pattern;}
```

## Environment

1. Ubuntu 16.04 LTS
2. Grakn Core 1.6.2
3. client-nodejs

## Reproducible Steps

Difficult to reproduce, but the use case is to launch multiple parallel processes inserting the same dataset with a lot of keys.

## Expected Output

Grakn error about key uniqeness.

## Actual Output

2 entities are inserted with the same key.
 
## Additional information

None.

**Comment by flyingsilverfin** [comment] 2020-02-24 10:05
Hey Samuel - do you have the distribution with this error committed still available? Would be interesting to know whether the attribute being returned has the same ID or is a different node altogether?

**Comment by richard-julien** [comment] 2020-06-12 22:30
Hi @flyingsilverfin, i have reproduce the bug. Some information.

```
  Stix-Domain sub entity,
    abstract,
    key internal_id_key,
    key stix_id_key,

  External-Reference sub Stix-Domain,
```

After concurrent insertion

```
grakn> match $x has stix_id_key "external-reference--7d34a529-13c5-5a22-87b2-e8de8613de4d"; get;
{$x id V156233768 isa External-Reference;}
{$x id V78016560 isa External-Reference;}
```

I still have the grakn database with this problem running if you need more information.

**Comment by flyingsilverfin** [comment] 2022-04-29 12:26
Closed since it's probably not an issue in 2.x, but please re-open if rediscovered!

**Closed by flyingsilverfin** 2022-04-29 12:26 UTC
Labels: type: bug
