### ISSUE TITLE
Slow undefining of rule

### ISSUE THREAD

**Issue by tomassabat** [vaticle/typedb#6491] opened 2021-12-14 16:01 UTC
## Description

Undefining of a rule takes over a minute. 

## Environment

1. OS: MacOS 11.2.3
2. TypeDB version: 2.5.0 on a local machine
3. TypeDB client: console

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Load the data from typedb-data-cti at commit `50a1b15`: https://github.com/typedb-osi/typedb-data-cti
2. Undefine a rule with `undefine rule mitigating-course-of-action-with-intrusion-set;`
3. Enter `commit`
4. TypeDB will be stuck for at least a minute, commit does eventually succeed

**Comment by krishnangovindraj** [comment] 2022-08-16 17:18
Managed to reproduce it on 2.9.0 to take ~45 seconds, but commits within seconds on 2.10.0 and 2.11.1
I'm going to close this since a lot of reasoner and some of rule-validation has changed since.

**Closed by krishnangovindraj** 2022-08-16 17:18 UTC
Labels: type: bug, priority: medium, domain: reasoner
