### ISSUE TITLE
Grakn: (Intermittent) Data integrity issue for large data import - too many entities, incorrect relationships

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#3896] opened 2018-09-21 23:54 UTC
_This issue was originally posted by @jmsfltchr  on 2018-05-08 17:02_.

My custom migration script threw an error because more concepts than expected were inserted into the database. There should be 285 stations, each with a unique naptan-id. In this case one naptan-id became related to 2 stations. There are also 286 stations in the db, one too many. Some stations have been inserted twice. This is after a match statement fails to return anything, so my code believes it doesn't exist in the db, and inserts a copy. Upon later querying, both are still present. In general, the data integrity was compromised in multiple ways. Unfortunately I was unable to replicate this issue.

**Comment by flyingsilverfin** [comment] 2021-06-15 15:59
Closing since not reproducible and outdated

**Closed by flyingsilverfin** 2021-06-15 15:59 UTC
Labels: type: bug
