### ISSUE TITLE
Transaction timeout reliably triggers too late under load

### ISSUE THREAD

**Issue by izmalk** [vaticle/typedb#6820] opened 2023-06-07 13:58 UTC
## Description

I created a lag generator to stress test TypeDB to make it respond to a query longer, then 5 minutes to trigger transaction duration timeout.

When it gets to iteration number 18 that takes too much time, we get the error
```
timestamp: 2023-06-07T13:50:39 Sending query# 18
Exception detected: [SRV29] Invalid Server Operation: Transaction exceeded maximum configured duration of '300' seconds.
```
But it takes us about 9-12 minutes to do so (since the start of transaction, and we spend less then a minute to get to the iteration number 18).

## Environment

1. OS (where TypeDB server runs): 12.6.6
2. TypeDB version (and platform): 2.18.0
3. TypeDB client: 2.18.0
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run the Python code: 
[heavy_loader_timeout.py.zip](https://github.com/vaticle/typedb/files/11677748/heavy_loader_timeout.py.zip)

## Expected Output

After 5 minutes since transaction opened we get the timeout error.

## Actual Output

We get the error much later.
I assume there could be some problems with time dilation due to TypeDB performance degradation during the stress test.
 
## Additional information

Server-side error:
```
13:49:36.492 [main] INFO com.vaticle.typedb.core.server.TypeDBServer - bootup completed in: 1810 ms
13:49:36.492 [main] INFO com.vaticle.typedb.core.server.TypeDBServer -
14:02:10.249 [typedb-scheduled::0] ERROR com.vaticle.typedb.core.server.TransactionService - [SRV29] Invalid Server Operation: Transaction exceeded maximum configured duration of '300' seconds.
```
Client-error:
```
timestamp: 2023-06-07T13:50:39 Sending query# 18
Exception detected: [SRV29] Invalid Server Operation: Transaction exceeded maximum configured duration of '300' seconds.
Counter: 18
Exiting
```
Exception detected at 14:02:10.

Sometimes (less than 30% of attempts) we can get Out of memory crash:
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "typedb-async-1::7"
12:51:51.781 [typedb-async-1::6] ERROR com.vaticle.typedb.core.server.TypeDBServer - [SRV04] Invalid Server Operation: Uncaught exception thrown at thread 'typedb-async-1::6':
'java.lang.OutOfMemoryError: Java heap space'
java.lang.OutOfMemoryError: Java heap space
...
```
But the client error in those cases is as follows:
```
timestamp: 2023-06-07T12:38:55 Sending query# 18
Exception detected: Client Error: Unable to connect to TypeDB server.
Counter: 18
Exiting
```

**Comment by shiladitya-mukherjee** [comment] 2023-07-13 09:43
Your queries cause the TypeDB server to run out of memory, and all guarantees (yes, even server-timeout, which are implemented using threads) are out of the window when the server runs out of memory.

Closing the issue.

**Comment by izmalk** [comment] 2023-07-13 09:55
> Your queries cause the TypeDB server to run out of memory, and all guarantees (yes, even server-timeout, which are implemented using threads) are out of the window when the server runs out of memory.
> 
> Closing the issue.

As I clearly state in my message - the OOM happens only about 30% of the time. And it leads to a completely different client-side error.

Have you been able to reproduce the issue?

And you didn't close the issue.

**Comment by shiladitya-mukherjee** [comment] 2023-07-13 10:06
> As I clearly state in my message - the OOM happens only about 30% of the time. And it leads to a completely different client-side error.

It means that 30% of the time, you get the error message that it's OOM. But 100% of the time, the Garbage Collector can't find enough space to run the next command. So the program just hangs.

> Have you been able to reproduce the issue?
Yes, and that too with various parameters.

> And you didn't close the issue.
I gave you some time to reply! :)

**Closed** 2023-07-13 10:10 UTC
Labels: priority: medium, domain: server

**Comment by izmalk** [comment] 2023-07-13 10:14
> It means that 30% of the time, you get the error message that it's OOM. But 100% of the time, the Garbage Collector can't find enough space to run the next command. So the program just hangs.

That explanation is much better, thanks! 
But it also looks like a significant problem. At the very least from the UX point of view.

**Comment by krishnangovindraj** [comment] 2023-07-13 10:15
Thanks for the great description & code @izmalk . This was very easy to reproduce.

The OOM error seems to be thrown only when the GC knows it's out of memory. When it's approaching that point, the GC is invoked very frequently - suspending all the threads when it does so and preventing/delaying the actual timeout from being executed.
