### ISSUE TITLE
Slow attribute comparison query in social network graph

### ISSUE THREAD

**Issue by kasper-piskorski** [vaticle/typedb#4936] opened 2019-02-19 14:44 UTC
```
match
$e1 isa periodic-event;
$e1 has start-date $sd1, has end-date $ed1;
$e2 isa periodic-event;
$e2 has start-date $sd2, has end-date $ed2;
$sd2 > $sd1;
$sd2 < $ed1;
$e1 id 'V245880';
$e2 id 'V540736';
$e1 != $e2;
get;
```

Slow plan: starts from $e2 -> results in upper bound for $sd1 and lower for $ed1
```
Greedy Plan = [
#1550591939298089[label:periodic-event], 
#1550591939298111[label:end-date], 
#1550591939298112[label:start-date], 
§e1[id:V245880], 
#1550591939298119[label:start-date], 
#1550591939298084[label:periodic-event], 
§e2[id:V540736], 
#1550591939298118[label:end-date], 
§e2[not-internal], 
§e2[not-internal], 

§e2-[isa]->#1550591939298113, 
#1550591939298113-[sub]->#1550591939298089, 
§e2<-[role-player:#1550591939298114 rels:@has-start-date roles:@has-start-date-owner]-#1550591939298090, 
#1550591939298090-[role-player:#1550591939298115 rels:@has-start-date roles:@has-start-date-value]->§sd2, 
#1550591939298115[neq:#1550591939298114], 
§sd2-[isa]->#1550591939298119, 
§e2<-[role-player:#1550591939298116 rels:@has-end-date roles:@has-end-date-owner]-#1550591939298092, 
#1550591939298092-[role-player:#1550591939298117 rels:@has-end-date roles:@has-end-date-value]->§ed2, 
#1550591939298117[neq:#1550591939298116], 
§ed2-[isa]->#1550591939298118, 
§ed1[not-internal], 
§sd2[value:<$ed1], 
§e1[not-internal], 
§e1[neq:§e2], 
§sd1[not-internal], 
§sd2[value:>$sd1], 
§e1-[isa]->#1550591939298106, 
#1550591939298106-[sub]->#1550591939298084, 
§e1<-[role-player:#1550591939298109 rels:@has-end-date roles:@has-end-date-owner]-#1550591939298087, 
#1550591939298087-[role-player:#1550591939298110 rels:@has-end-date roles:@has-end-date-value]->§ed1, 
#1550591939298110[neq:#1550591939298109], 
§ed1-[isa]->#1550591939298111, 
§e1<-[role-player:#1550591939298107 rels:@has-start-date roles:@has-start-date-owner]-#1550591939298085, 
#1550591939298085-[role-player:#1550591939298108 rels:@has-start-date roles:@has-start-date-value]->§sd1, 
#1550591939298108[neq:#1550591939298107], 
§sd1-[isa]->#1550591939298112]
```

Fast plan - starts from $e1 resulting in upper and lower bound for $sd2
```
Greedy Plan = [
#1550591939298069[label:end-date], 
#1550591939298077[label:start-date], 
§e1[id:V245880], 
#1550591939298076[label:end-date], 
#1550591939298070[label:start-date], 
§e2[id:V540736], 
#1550591939298042[label:periodic-event], 
#1550591939298047[label:periodic-event], 
§e1[not-internal], 

§e1-[isa]->#1550591939298064, 
#1550591939298064-[sub]->#1550591939298042, 
§e1<-[role-player:#1550591939298065 rels:@has-start-date roles:@has-start-date-owner]-#1550591939298043, 
#1550591939298043-[role-player:#1550591939298066 rels:@has-start-date roles:@has-start-date-value]->§sd1, 
#1550591939298066[neq:#1550591939298065], 
§sd1[not-internal], 
§sd1-[isa]->#1550591939298070, 
§e1<-[role-player:#1550591939298067 rels:@has-end-date roles:@has-end-date-owner]-#1550591939298045, 
#1550591939298045-[role-player:#1550591939298068 rels:@has-end-date roles:@has-end-date-value]->§ed1, 
#1550591939298068[neq:#1550591939298067], 
§ed1[not-internal], 
§ed1-[isa]->#1550591939298069, 
§e2[not-internal], 
§e2[neq:§e1], 
§e2[not-internal], 
§sd2[value:>$sd1], 
§sd2[value:<$ed1], 
§e2-[isa]->#1550591939298071, 
#1550591939298071-[sub]->#1550591939298047, 
§e2<-[role-player:#1550591939298072 rels:@has-start-date roles:@has-start-date-owner]-#1550591939298048, 
#1550591939298048-[role-player:#1550591939298073 rels:@has-start-date roles:@has-start-date-value]->§sd2, 
#1550591939298073[neq:#1550591939298072], 
§sd2-[isa]->#1550591939298077, 
§e2<-[role-player:#1550591939298074 rels:@has-end-date roles:@has-end-date-owner]-#1550591939298050, 
#1550591939298050-[role-player:#1550591939298075 rels:@has-end-date roles:@has-end-date-value]->§ed2, 
#1550591939298075[neq:#1550591939298074], 
§ed2-[isa]->#1550591939298076]

**Comment by krishnangovindraj** [comment] 2023-01-11 16:09
Closing outdated report, hard to reproduce, probably fixed since the planner has changed so much since.

**Closed by krishnangovindraj** 2023-01-11 16:09 UTC
