### ISSUE TITLE
Grakn: Slow match query

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#4225] opened 2018-09-22 01:31 UTC
_This issue was originally posted by @tomassabat  on 2018-08-19 17:30_.

Load dataset called "grakn-dist-1.3.0 [Tomas Biomed v2]" (keyspace "disease_james") in folder Datasets in Dropbox and run the query below. Queries take very long to return. 
```
match 
$pr isa protein; 
$pr2 isa protein;
$pr != $pr;
$ti isa tissue, has tissue-name "bone marrow"; 
$ppi (interacting-protein: $pr, interacting-protein: $pr2) isa protein-protein-interaction; 
(biomolecular-process: $ppr, tissue-context: $ti) isa process-localisation;
limit 5; get; 
```
 
```
match 
$di isa disease, has disease-name "Asthma"; 
$ti isa tissue, has tissue-name "breast";
$dr isa drug;
$pr isa protein;
$pr2 isa protein; 
(associated-disease: $di, associated-protein: $pr) isa protein-disease-association; 
$r (interacting-protein: $pr, interacting-protein: $pr) isa protein-protein-interaction; 
(tissue-context: $ti, biomolecular-process: $r) isa process-localisation; 
(target-protein: $pr, interacted-drug: $dr) isa drug-protein-interaction; 
(target-protein: $pr2, interacted-drug: $dr) isa drug-protein-interaction; 
limit 20; get; 
```

**Comment by krishnangovindraj** [comment] 2023-01-11 17:19
@tomassabat , Do you have a link to this dataset updated to typeql?
Else, we'll just close this since it's hard to reproduce (and unlikely to still be a problem)

**Comment by tomassabat** [comment] 2023-01-12 11:08
@krishnangovindraj: This is 4.5 years ago so really not sure if worth looking into - I don't know why the referred file is not available in the Datasets folder. It may be this one: https://www.dropbox.com/s/gu7fto79crs4q9g/tomas-disease-network-dataset%282%29.zip?dl=0

**Comment by krishnangovindraj** [comment] 2023-01-12 11:11
In that case, I'll just close this. Thanks!

**Closed by krishnangovindraj** 2023-01-12 11:11 UTC
Labels: type: feature, status: invalid, status: blocked
