### ISSUE TITLE
Automatically/periodically delete disconnected concepts

### ISSUE THREAD

**Issue by FrankUrbach** [vaticle/typedb#6464] opened 2021-11-01 10:47 UTC
## Problem to Solve

During data loading and update over time, it is possible that we end up with orphaned/disconnected data. This could be entities, or attributes (relations always have at least 1 role player). 

## Current Workaround

From the applicaton side, we can manually clean up attributes and entities periodically.
We can see how this looks for attributes in the following post: https://forum.vaticle.com/t/how-to-remove-attributes-that-doesnt-have-any-edge-to-an-entity/2653

Something very similar can be done for entities that are disconnected.

## Proposed Solution

Introduce server-side functionality to perform this cleanup, rather than requiring each user implement this feature themselves.

## Additional informations 

It would be great if in the configuration file we can set whether a clean up runs periodically, on demand, or continuously (eg. a transaction performs the cleanup as part of the commit process? - this could be more efficient since we only have to check the modified concepts!). Alternatively, should be configurable from transaction options.

**Comment by alexjpwalker** [comment] 2021-11-01 13:57
I can think of one case where orphaned attributes could sting us pretty badly. If you're managing a user accounts system and someone makes a legal GDPR request for their data to be deleted, then how do we define "deleted"? is deleting the person entity enough, or do we also need to delete their name? what if someone else owns the same name?

we could say that the name isn't identifying information, but what if it's, say, "Mark Zuckerberg"?

**Comment by flyingsilverfin** [comment] 2021-11-02 14:35
This is a duplicate of https://github.com/vaticle/typedb/issues/6389 , so we close this and generalise the other issue

**Closed by flyingsilverfin** 2021-11-02 14:35 UTC
Labels: type: feature, priority: medium
