### ISSUE TITLE
Retrieving all attribute types owned by a concept type

### ISSUE THREAD

**Issue by MCSH** [vaticle/typedb#4664] opened 2018-11-26 20:51 UTC
Hello,

I already brought this up in slack. I wanted a way to list all attributes for a given entity, the solution was running the following query:

```
match person has $x; get;
```

However, running that will produce

```
>>> match person has $x; get $x;
'has' argument '$x' requires a label
```

**Comment by sorsaffari** [comment] 2018-11-26 21:30
@kasper-piskorski This is a use case that should be included in our docs. Do you think it could make it to 1.5?

**Comment by kasper-piskorski** [comment] 2018-11-28 09:54
It's a currently unsupported feature. At the moment you can have:

$var has <type> ($v | predicate) - fetch instances with attribute of specific type (and satisfying predicate)
$var has <type> - fetch types that can have a specific attribute

Unlikely to be included in the 1.5.

**Comment by sorsaffari** [comment] 2018-11-29 12:36
@MCSH here is how you'd do this with the client Python:

```python
  client = grakn.Grakn(uri = "localhost:48555")
  with client.session(keyspace = "phone_calls") as ses:
    with ses.transaction(grakn.TxType.READ) as transaction:
        answer_iterator = transaction.query("match $x sub person; get;")

        for answer in answer_iterator:
          attr_iterator = answer.map().get("x").attributes()

          for attr in attr_iterator:
            print(attr.label())
```

**Comment by sorsaffari** [comment] 2018-11-29 15:13
@MCSH similarly with the client Node.js:

```
async function printAttributesOfPerson() {
  const grakn = new Grakn("localhost:48555");
  const session = await grakn.session((keyspace = "phone_calls"));
  const transaction = await session.transaction(Grakn.txType.READ);

  let answerIterator = await transaction.query("match $x sub sub-person; get;");

  let answer = await answerIterator.next();
  while (answer != null) {
    attrIterator = await answer.map().get("x").attributes();

    let attr = await attrIterator.next();
    while (attr != null) {
      console.log(await attr.label());
      attr = await attrIterator.next();
    }
    answer = await answerIterator.next();
  }

  transaction.close();
  session.close();
}
```

**Comment by MCSH** [comment] 2018-11-29 15:58
Thank you so much.

**Comment by sorsaffari** [comment] 2018-11-29 18:52
You're most welcome :)

**Comment by sorsaffari** [comment] 2019-06-28 09:21
@haikalpribadi do you think could resolve this in the next release? or the one after that?
more developers are asking for it

**Comment by haikalpribadi** [comment] 2019-06-28 10:02
You are already able to do this (I think for a very long time), by querying:
```
match $x isa person, has attribute $y; get;
```

By specifying `attribute` which is the "super-type" of all attributes, you will retrieve all attributes of a given entity. @sorsaffari @MCSH 

I will close this issue now.

**Comment by sorsaffari** [comment] 2019-06-28 11:15
@haikalpribadi the issue is about retrieving attribute types owned by a given concept type, not the instances.

**Comment by haikalpribadi** [comment] 2019-06-28 11:49
Ah, sorry I misunderstood the issue. Got it!

**Comment by flyingsilverfin** [comment] 2019-10-15 16:20
Related to #4562, which followed with more tests indicates this is now possible but can be buggy when it comes to inheritance!

**Comment by gabywang5** [comment] 2020-06-08 07:41
> @MCSH here is how you'd do this with the client Python:
> 
> ```python
>   client = grakn.Grakn(uri = "localhost:48555")
>   with client.session(keyspace = "phone_calls") as ses:
>     with ses.transaction(grakn.TxType.READ) as transaction:
>         answer_iterator = transaction.query("match $x sub person; get;")
> 
>         for answer in answer_iterator:
>           attr_iterator = answer.map().get("x").attributes()
> 
>           for attr in attr_iterator:
>             print(attr.label())
> ```

Hi, sorsaffari, I use your code above to retrieve all the attributes that a person type instance can have. The code below is almost the same as yours above, but I specified the session type as read().

But, after I run the code, it shows "AttributeError: 'EntityType' object has no attribute 'attributes'".

My code is here:
```python
from grakn.client import GraknClient

with GraknClient(uri="localhost:48555") as client:
    with client.session(keyspace="phone_calls") as ses:
        with ses.transaction().read() as transaction:
            answer_iterator = transaction.query("match $x sub person; get;")

            for answer in answer_iterator:
                attr_iterator = answer.map().get("x").attributes()

                for attr in attr_iterator:
                    print(attr.label())
```

I feel so confused. I would be grateful if you can help. Thanks. ^_^

**Comment by flyingsilverfin** [comment] 2020-06-08 09:09
@gabywang5 if you're on version 1.7.x you need to convert your concept to `Remote` concept type, or those methods won't be available - see https://dev.grakn.ai/docs/concept-api/overview

**Comment by gabywang5** [comment] 2020-06-09 03:04
@flyingsilverfin Thank you so much. After I convert the concept to Remote concept type, all the methods work. ^_^

By the way, I wonder what the "local" and "remote" really mean? Because the grakn server directly runs on my laptop and fetching information has no network latency. I think it is sort of local. Right?When I submit a query through the session, it directly fetches answers from my local server without network round-trip. Thus, I hardly understand why should I use a remote concept method when I just need to refer to my local server.

I noticed that the most significant difference between local and remote is that the local method only needs one go and it may become out of date; while the remote one always retrieves the latest information.  I guess there is the occasion where we are allowed to deploy 2 versions of server(a local one and a remote one which need network travel) ? 

I'm not sure I have clearly expressed my confusion because my brain is messed up...

Thank you again for your help.

**Comment by flyingsilverfin** [comment] 2020-06-09 11:18
`Local` concepts are stateful versions of concepts that cannot do any work over the network - they are just containers of values that have been fetched from the server with a query.

`Remote` concepts have full access to the database over the network, and each operation will cost you at least a round trip to the database - this really starts to matter once your grakn server is not located on the same machine as your client. If everything is local it's not too different.

**Comment by gabywang5** [comment] 2020-06-10 01:30
@flyingsilverfin Thanks for making these concepts much clearer in my head.

**Comment by alexjpwalker** [comment] 2020-06-17 17:38
This is also an issue when running `match person key $x`

**Comment by quang-nnguyen** [comment] 2020-06-18 06:53
Thank @gabywang5 for bringing this issue up again. I fell into the same problem and could not resolve it myself. Clearly the version 1.7.x came with some changes that made the old implementation unable to work. Also thank @flyingsilverfin for your suggestion of `Remote` concept. It works nicely. 

Nonetheless, it took me a while to figure out how to implement it since I'm new to Grakn. So I'd like to just post the final answer to this issue below for anyone who runs into it in the future:

```python
from grakn.client import GraknClient

with GraknClient(uri="localhost:48555") as client:
    with client.session(keyspace="phone_calls") as ses:
        with ses.transaction().read() as transaction:
            answer_iterator = transaction.query("match $x sub person; get;")

            for answer in answer_iterator:
                attr_iterator = answer.map().get("x").as_remote(transaction).attributes()

                for attr in attr_iterator:
                    print(attr.label())
```

Use `as_remote(tx)` with `tx` being the `transaction` in the process. Read more in [here](https://github.com/graknlabs/client-python/blob/master/grakn/service/Session/Concept/Concept.py)

**Comment by flyingsilverfin** [comment] 2021-04-22 15:14
In Grakn 2.0 you can use `owns` to retrieve attribute types owned

**Closed by flyingsilverfin** 2021-04-22 15:14 UTC
Labels: type: feature
