### ISSUE TITLE
Aggregate count returns wrong result

### ISSUE THREAD

**Issue by grabl** [vaticle/typedb#4342] opened 2018-09-22 01:39 UTC
_This issue was originally posted by @lolski  on 2018-09-19 17:27_.

Query: 
```
match $i1 isa issue; $i2 isa issue; 
(depended: $i1, dependant: $i2) isa dependency; 
$p1 isa repository; $p2 isa repository; 
$p1 != $p2; 
($i1, $p1) isa contains; 
($i2, $p2) isa contains; 
aggregate count $i1; 
```
 Returns: 25 Expected: 9 Dataset: `Dropbox > Datasets > grakn-core-1.4.0-SNAPSHOT-with-github-data.zip`

**Comment by flyingsilverfin** [comment] 2021-04-22 15:12
Closing as not relevant anymore, cannot reproduce from distribution 2.0

**Closed by flyingsilverfin** 2021-04-22 15:12 UTC
Labels: type: bug
